-- Pauta
CREATE TABLE pauta (
    id        BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    titulo    VARCHAR(200)  NOT NULL,
    descricao VARCHAR(2000),
    criada_em TIMESTAMPTZ   NOT NULL
);

-- Sessão de votação (uma por pauta)
CREATE TABLE sessao_votacao (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    pauta_id     BIGINT      NOT NULL UNIQUE REFERENCES pauta (id),
    abertura     TIMESTAMPTZ NOT NULL,
    encerramento TIMESTAMPTZ NOT NULL
);

-- Voto (um por associado por sessão)
CREATE TABLE voto (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    sessao_id     BIGINT      NOT NULL REFERENCES sessao_votacao (id),
    associado_id  VARCHAR(64) NOT NULL,
    escolha       VARCHAR(3)  NOT NULL CHECK (escolha IN ('SIM', 'NAO')),
    registrado_em TIMESTAMPTZ NOT NULL,
    UNIQUE (sessao_id, associado_id)
);
